// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEHFvcNM7hoEeeFQix58eypHCzR3l16UM',
    appId: '1:714725259912:web:947c25f99c34ccd9f77d3d',
    messagingSenderId: '714725259912',
    projectId: 'ethiopian-names-app',
    authDomain: 'ethiopian-names-app.firebaseapp.com',
    storageBucket: 'ethiopian-names-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnar0UrSwkp10WNtIHX2Xs-pwvpBygjos',
    appId: '1:714725259912:android:b153639557af00ecf77d3d',
    messagingSenderId: '714725259912',
    projectId: 'ethiopian-names-app',
    storageBucket: 'ethiopian-names-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFUHw41iqYVrRLc8S4HKhMET-iBARkKTk',
    appId: '1:714725259912:ios:a3ef632dd46934e1f77d3d',
    messagingSenderId: '714725259912',
    projectId: 'ethiopian-names-app',
    storageBucket: 'ethiopian-names-app.firebasestorage.app',
    iosBundleId: 'com.example.ethiopianTransliterator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFUHw41iqYVrRLc8S4HKhMET-iBARkKTk',
    appId: '1:714725259912:ios:a3ef632dd46934e1f77d3d',
    messagingSenderId: '714725259912',
    projectId: 'ethiopian-names-app',
    storageBucket: 'ethiopian-names-app.firebasestorage.app',
    iosBundleId: 'com.example.ethiopianTransliterator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEHFvcNM7hoEeeFQix58eypHCzR3l16UM',
    appId: '1:714725259912:web:b5066d47bf517e92f77d3d',
    messagingSenderId: '714725259912',
    projectId: 'ethiopian-names-app',
    authDomain: 'ethiopian-names-app.firebaseapp.com',
    storageBucket: 'ethiopian-names-app.firebasestorage.app',
  );
}
